/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databaseproject1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.Timer;
import java.util.TimerTask;
import javax.management.modelmbean.ModelMBean;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.TableView;
import javax.swing.text.html.HTML;

/**
 *
 * @author CompuMall
 */
public class Cars extends javax.swing.JFrame {

    Connection con;
    int currRow;
    int carSelectedRowID;

    /**
     * Creates new form Cars
     */
    public Cars() {
        initComponents();
        createConnection();
        this.setLocationRelativeTo(null);
    }

    void createConnection() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "khashana44Wlv");
//          THIS HOW TO CREATE STATMENT AND GET DATA  
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from cars");
//            while there is one more than one row
            while (rs.next()) {
                String carId = rs.getString("carID");
                String brand = rs.getString("carBrand");
                String model = rs.getString("carModel");
                String ownerId = rs.getString("ownerID");

                System.out.println(carId + " | " + brand + " | " + model + " | " + ownerId);
            }

        } catch (SQLException ex) {
            Logger.getLogger(DatabaseProject1.class.getName()).log(Level.SEVERE, null, ex);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DatabaseProject1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adminWelcome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        carBrand = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addNewCarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarsTablev = new javax.swing.JTable();
        editCurrCarBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        editCarBrand = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        refreshCarsTable = new javax.swing.JButton();
        ResetAddNewCarInputsBtn = new javax.swing.JButton();
        deleteCurrCarBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alertsLabel = new javax.swing.JLabel();
        carModel = new javax.swing.JTextField();
        editCarModel = new javax.swing.JTextField();
        ownerID = new javax.swing.JTextField();
        editOwnerID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        adminWelcome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminWelcome.setForeground(new java.awt.Color(204, 204, 204));
        adminWelcome.setText("Cars Dashboard");
        adminWelcome.setAlignmentX(0.5F);

        jSeparator1.setBackground(new java.awt.Color(0, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Brand");

        carBrand.setBackground(new java.awt.Color(51, 51, 51));
        carBrand.setForeground(new java.awt.Color(204, 204, 204));
        carBrand.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        carBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBrandActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Model");

        addNewCarBtn.setText("Add");
        addNewCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCarBtn(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));

        CarsTablev.setBackground(new java.awt.Color(51, 51, 51));
        CarsTablev.setForeground(new java.awt.Color(204, 204, 204));
        CarsTablev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Brand", "Model", "OwnerID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CarsTablev.setGridColor(new java.awt.Color(204, 204, 204));
        CarsTablev.setSelectionBackground(new java.awt.Color(51, 51, 51));
        CarsTablev.setSelectionForeground(new java.awt.Color(204, 204, 204));
        CarsTablev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarsTablevMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CarsTablev);

        editCurrCarBtn.setText("Edit");
        editCurrCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCurrCarBtn(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Brand");

        editCarBrand.setBackground(new java.awt.Color(51, 51, 51));
        editCarBrand.setForeground(new java.awt.Color(204, 204, 204));
        editCarBrand.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        editCarBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCarBrandActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Model");

        refreshCarsTable.setText("Refresh");
        refreshCarsTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshCarsTableActionPerformed(evt);
            }
        });

        ResetAddNewCarInputsBtn.setText("Reset");
        ResetAddNewCarInputsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetAddNewCarInputsBtn(evt);
            }
        });

        deleteCurrCarBtn.setText("Delete");
        deleteCurrCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCurrCarBtn(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("OwnerID");

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("OwnerID");

        alertsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alertsLabel.setForeground(new java.awt.Color(102, 153, 255));

        carModel.setBackground(new java.awt.Color(51, 51, 51));
        carModel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));

        editCarModel.setBackground(new java.awt.Color(51, 51, 51));
        editCarModel.setForeground(new java.awt.Color(204, 204, 204));
        editCarModel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));

        ownerID.setBackground(new java.awt.Color(51, 51, 51));
        ownerID.setForeground(new java.awt.Color(204, 204, 204));
        ownerID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));

        editOwnerID.setBackground(new java.awt.Color(51, 51, 51));
        editOwnerID.setForeground(new java.awt.Color(204, 204, 204));
        editOwnerID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("<--");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alertsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(carBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(editCarBrand))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refreshCarsTable, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editCarModel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(carModel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ownerID)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(editOwnerID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editCurrCarBtn)
                                    .addComponent(addNewCarBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResetAddNewCarInputsBtn)
                                    .addComponent(deleteCurrCarBtn)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(adminWelcome)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adminWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewCarBtn)
                    .addComponent(ResetAddNewCarInputsBtn)
                    .addComponent(carModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCarBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCurrCarBtn)
                    .addComponent(deleteCurrCarBtn)
                    .addComponent(editCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editOwnerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refreshCarsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alertsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteCurrCarBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCurrCarBtn
        //        int currRow = adminsTablev.getSelectedRow();
        String getRowID = (String) CarsTablev.getValueAt(CarsTablev.getSelectedRow(), 0);
        Statement stmt;
        try {
            stmt = con.createStatement();
            String deleteCar = "Delete from cars where carID = '" + getRowID + "'";
            stmt.executeUpdate(deleteCar);
            refreshCarsTableActionPerformed(evt);
            editCarBrand.setText("");
            editCarModel.setText("");
            editOwnerID.setText("");
            CarsTablev.clearSelection();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(DB2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteCurrCarBtn

    private void ResetAddNewCarInputsBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetAddNewCarInputsBtn
        // TODO add your handling code here:
        carModel.setText("");
        carBrand.setText("");
        ownerID.setText("");
    }//GEN-LAST:event_ResetAddNewCarInputsBtn

    private void refreshCarsTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshCarsTableActionPerformed
        DefaultTableModel carsTable = (DefaultTableModel) CarsTablev.getModel();
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from cars");
            int rowCount = -1;
            while (rs.next()) {
                rowCount++;
                String carId = rs.getString("carID");
                String carBrand = rs.getString("carBrand");
                String carModel = rs.getString("carModel");
                String ownerId = rs.getString("ownerId");
                carsTable.setRowCount(rowCount);
                carsTable.addRow(new Object[]{carId, carBrand, carModel, ownerId});
            }
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(DB2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshCarsTableActionPerformed

    private void editCarBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCarBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editCarBrandActionPerformed

    private void editCurrCarBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCurrCarBtn
        try {
            String brand = editCarBrand.getText();
            String model = editCarModel.getText();
            String ownerId = editOwnerID.getText();
            Statement stmt = con.createStatement();
            String editCar = "UPDATE cars SET carBrand = '" + brand + "', carModel = '" + model + "', ownerId = '" + ownerId + "' WHERE carID = '" + carSelectedRowID + "'";
            try {
                stmt.execute(editCar);
                editCarBrand.setText("");
                editCarModel.setText("");
                editOwnerID.setText("");
                CarsTablev.clearSelection();
                carSelectedRowID = -1;
            } catch (SQLException ex) {
                alertsLabel.setText("There's no Customer with that ID!");
                Timer timer = new Timer();
                timer.schedule(new TimerTask() {
                    @Override
                    public void run() {
                        alertsLabel.setText("");
                    }
                }, 2000);
            }

            refreshCarsTableActionPerformed(evt);
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(DB2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editCurrCarBtn

    private void CarsTablevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarsTablevMouseClicked
        // TODO add your handling code here:
        DefaultTableModel carsTable = (DefaultTableModel) CarsTablev.getModel();
//        currRow = CarsTablev.getSelectedRow();
        String editCarBraand = (String) carsTable.getValueAt(CarsTablev.getSelectedRow(), 1);
        String editCarModeel = (String) carsTable.getValueAt(CarsTablev.getSelectedRow(), 2);
        String editOwnerId = (String) carsTable.getValueAt(CarsTablev.getSelectedRow(), 3);
        carSelectedRowID = Integer.parseInt((String) carsTable.getValueAt(CarsTablev.getSelectedRow(), 0));
        editCarBrand.setText(editCarBraand);
        editCarModel.setText(editCarModeel);
        editOwnerID.setText(editOwnerId);
    }//GEN-LAST:event_CarsTablevMouseClicked

    private void addNewCarBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCarBtn
        try {
            //  Adding car Operation
            String brand = carBrand.getText();
            String model = carModel.getText();
            String ownerId = ownerID.getText();
            Statement stmt = con.createStatement();
            String addCar = "INSERT INTO cars (carBrand, carModel, ownerID) VALUES ('" + brand + "', '" + model + "', '" + ownerId + "')";
            try {
                stmt.execute(addCar);
            } catch (SQLException ex) {
                alertsLabel.setText("There's no Customer with that ID!");
                Timer timer = new Timer();
                timer.schedule(new TimerTask() {
                    @Override
                    public void run() {
                        alertsLabel.setText("");
                    }
                }, 2000);
            }

            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(DB2.class.getName()).log(Level.SEVERE, null, ex);
        }
        refreshCarsTableActionPerformed(evt);
    }//GEN-LAST:event_addNewCarBtn

    private void carBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carBrandActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        FullData fd = new FullData();
        fd.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CarsTablev;
    private javax.swing.JButton ResetAddNewCarInputsBtn;
    private javax.swing.JButton addNewCarBtn;
    private javax.swing.JLabel adminWelcome;
    private javax.swing.JLabel alertsLabel;
    private javax.swing.JTextField carBrand;
    private javax.swing.JTextField carModel;
    private javax.swing.JButton deleteCurrCarBtn;
    private javax.swing.JTextField editCarBrand;
    private javax.swing.JTextField editCarModel;
    private javax.swing.JButton editCurrCarBtn;
    private javax.swing.JTextField editOwnerID;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField ownerID;
    private javax.swing.JButton refreshCarsTable;
    // End of variables declaration//GEN-END:variables
}
