package databaseproject1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.management.modelmbean.ModelMBean;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.TableView;
import javax.swing.text.html.HTML;

public class DB2 extends javax.swing.JFrame {

    Connection con;
    int currRow;
    int adminSelectedRowID;

    public DB2() {
        initComponents();
        createConnection();
        this.setLocationRelativeTo(null);
    }

    void createConnection() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "khashana44Wlv");
//          THIS HOW TO CREATE STATMENT AND GET DATA  
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from admins");
//            while there is one more than one row
            while (rs.next()) {
                String adminId = rs.getString("adminID");
                String name = rs.getString("adminName");
                String password = rs.getString("adminPassword");
                System.out.println(adminId + " | " + name + " | " + password);
            }

        } catch (SQLException ex) {
            Logger.getLogger(DatabaseProject1.class.getName()).log(Level.SEVERE, null, ex);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DatabaseProject1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        adminName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adminPass = new javax.swing.JPasswordField();
        addNewAdminBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminsTablev = new javax.swing.JTable();
        editAdminPass = new javax.swing.JPasswordField();
        editCurrAdminBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        editAdminName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        refreshAdminsTable = new javax.swing.JButton();
        ResetAddNewAdminInputsBtn = new javax.swing.JButton();
        deleteCurrAdminBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Admins Dashboard");
        jLabel1.setAlignmentX(0.5F);

        jSeparator1.setBackground(new java.awt.Color(0, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Full Name");

        adminName.setBackground(new java.awt.Color(51, 51, 51));
        adminName.setForeground(new java.awt.Color(204, 204, 204));
        adminName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        adminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNameActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Password");

        adminPass.setBackground(new java.awt.Color(51, 51, 51));
        adminPass.setForeground(new java.awt.Color(204, 204, 204));
        adminPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        adminPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPassActionPerformed(evt);
            }
        });

        addNewAdminBtn.setText("Add");
        addNewAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewAdminBtn(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));

        adminsTablev.setBackground(new java.awt.Color(51, 51, 51));
        adminsTablev.setForeground(new java.awt.Color(204, 204, 204));
        adminsTablev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        adminsTablev.setGridColor(new java.awt.Color(204, 204, 204));
        adminsTablev.setSelectionBackground(new java.awt.Color(51, 51, 51));
        adminsTablev.setSelectionForeground(new java.awt.Color(204, 204, 204));
        adminsTablev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminsTablevMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adminsTablev);

        editAdminPass.setBackground(new java.awt.Color(51, 51, 51));
        editAdminPass.setForeground(new java.awt.Color(204, 204, 204));
        editAdminPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        editAdminPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAdminPassActionPerformed(evt);
            }
        });

        editCurrAdminBtn.setText("Edit");
        editCurrAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCurrAdminBtn(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Full Name");

        editAdminName.setBackground(new java.awt.Color(51, 51, 51));
        editAdminName.setForeground(new java.awt.Color(204, 204, 204));
        editAdminName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        editAdminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAdminNameActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Password");

        refreshAdminsTable.setText("Refresh");
        refreshAdminsTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAdminsTableActionPerformed(evt);
            }
        });

        ResetAddNewAdminInputsBtn.setText("Reset");
        ResetAddNewAdminInputsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetAddNewAdminInputsBtn(evt);
            }
        });

        deleteCurrAdminBtn.setText("Delete");
        deleteCurrAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCurrAdminBtn(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("<--");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editAdminName)
                            .addComponent(adminName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminPass)
                            .addComponent(editAdminPass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editCurrAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addNewAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(refreshAdminsTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ResetAddNewAdminInputsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteCurrAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addNewAdminBtn)
                            .addComponent(ResetAddNewAdminInputsBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editAdminPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editCurrAdminBtn)
                            .addComponent(deleteCurrAdminBtn))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(refreshAdminsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewAdminBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewAdminBtn
        try {
//            Adding admin Operation
            String name = adminName.getText();
            String pass = adminPass.getText();
            Statement stmt = con.createStatement();
            String addAdmin = "INSERT INTO admins (adminName, adminPassword) VALUES ('" + name + "', '" + pass + "')";
            stmt.execute(addAdmin);

            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(DB2.class.getName()).log(Level.SEVERE, null, ex);
        }
        refreshAdminsTableActionPerformed(evt);
    }//GEN-LAST:event_addNewAdminBtn

    private void adminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNameActionPerformed

    private void adminPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPassActionPerformed

    private void editAdminPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAdminPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editAdminPassActionPerformed

    private void editCurrAdminBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCurrAdminBtn
        try {
            String name = editAdminName.getText();
            String pass = editAdminPass.getText();
            Statement stmt = con.createStatement();
            String editAdmin = "UPDATE admins SET adminName = '" + name + "', adminPassword = '" + pass + "' WHERE adminID = '" + adminSelectedRowID + "'";
            stmt.execute(editAdmin);
            editAdminName.setText("");
            editAdminPass.setText("");
            adminsTablev.clearSelection();
            adminSelectedRowID = -1;
            refreshAdminsTableActionPerformed(evt);
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(DB2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editCurrAdminBtn

    private void editAdminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAdminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editAdminNameActionPerformed

    private void refreshAdminsTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshAdminsTableActionPerformed
        DefaultTableModel adminsTable = (DefaultTableModel) adminsTablev.getModel();
        try {
            Statement stmt = con.createStatement();

//          Dispaying Data To The Table
            ResultSet rs = stmt.executeQuery("select * from admins");
            int rowCount = -1;
            while (rs.next()) {
                rowCount++;
                String adminId = rs.getString("adminID");
                String adminName = rs.getString("adminName");
                String AdminPassword = rs.getString("adminPassword");
//                System.out.println(adminId + " | " + adminName + " | " + AdminPassword);
                adminsTable.setRowCount(rowCount);
                adminsTable.addRow(new Object[]{adminId, adminName, AdminPassword});
            }
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(DB2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_refreshAdminsTableActionPerformed

    private void ResetAddNewAdminInputsBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetAddNewAdminInputsBtn
        // TODO add your handling code here:
        adminPass.setText("");
        adminName.setText("");
    }//GEN-LAST:event_ResetAddNewAdminInputsBtn

    private void deleteCurrAdminBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCurrAdminBtn
//        int currRow = adminsTablev.getSelectedRow();
        String getRowID = (String) adminsTablev.getValueAt(adminsTablev.getSelectedRow(), 0);
        Statement stmt;
        try {
            stmt = con.createStatement();
            String deleteAdmin = "Delete from admins where adminID = '" + getRowID + "'";
            stmt.executeUpdate(deleteAdmin);
            refreshAdminsTableActionPerformed(evt);
            editAdminName.setText("");
            editAdminPass.setText("");
            adminsTablev.clearSelection();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(DB2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteCurrAdminBtn

    private void adminsTablevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminsTablevMouseClicked
        // TODO add your handling code here:
        DefaultTableModel adminsTable = (DefaultTableModel) adminsTablev.getModel();
//        currRow = adminsTablev.getSelectedRow();
        String editAdmnName = (String) adminsTable.getValueAt(adminsTablev.getSelectedRow(), 1);
        String editAdmnPass = (String) adminsTable.getValueAt(adminsTablev.getSelectedRow(), 2);
        adminSelectedRowID = Integer.parseInt((String) adminsTable.getValueAt(adminsTablev.getSelectedRow(), 0));
        editAdminName.setText(editAdmnName);
        editAdminPass.setText(editAdmnPass);
    }//GEN-LAST:event_adminsTablevMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        FullData Fd = new FullData();
        Fd.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DB2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetAddNewAdminInputsBtn;
    private javax.swing.JButton addNewAdminBtn;
    private javax.swing.JTextField adminName;
    private javax.swing.JPasswordField adminPass;
    private javax.swing.JTable adminsTablev;
    private javax.swing.JButton deleteCurrAdminBtn;
    private javax.swing.JTextField editAdminName;
    private javax.swing.JPasswordField editAdminPass;
    private javax.swing.JButton editCurrAdminBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton refreshAdminsTable;
    // End of variables declaration//GEN-END:variables
}
